BUG: use last __init__ to document class variables
pdoc3/pdoc pull request #249
Opened 2020-08-31 04:52 UTC by nosewings

Fixes #248.

2020-08-31 10:44 UTC, kernc requested changes
Add/amend a unit test. Maybe even this one:
https://github.com/pdoc3/pdoc/blob/6cfbc4fa0f09de79c51aedb435707a4dcd3b01b9/pdoc/test/__init__.py#L887

2020-08-31 10:44 UTC, kernc commented on pdoc/__init__.py
> -            for node in tree.body:
Ugh. Can't we make this just:
```py
for node in reversed(tree.body):
```

2020-08-31 22:15 UTC, nosewings commented
I've gone ahead and made the requested changes.

2020-08-31 22:49 UTC, kernc commented on pdoc/test/__init__.py
> +        """dummy1"""
Maybe also change these two lines to `pass` so as to not be confusing as we don't really need/check them?

2020-09-05 21:11 UTC, nosewings commented
Okay, I've done that.

2020-09-08 23:38 UTC, kernc approved these changes

2020-09-08 23:38 UTC, kernc commented
Perfect, thanks!

2020-09-08 23:38 UTC, merged