ENH: Show new type names for function signatures
pdoc3/pdoc pull request #254
Opened 2020-09-04 14:05 UTC by TristanCacqueray

Fixes: #253

2020-09-04 14:23 UTC, kernc requested changes
Thanks for the PR! While you're reimplementing `formatannotation()`, can you maybe have a look if https://github.com/pdoc3/pdoc/issues/231 is an easy fix?

2020-09-04 14:23 UTC, kernc commented on pdoc/__init__.py
> +def formatannotation(annot):
Rename to `_formatannotation` as this will not be public API.

2020-09-04 14:23 UTC, kernc commented on pdoc/test/example_pkg/_resolve_typing_forwardrefs/evaluated.py
> +MyType = NewType('MyType', str)
Why touch this test also?

2020-09-04 14:23 UTC, kernc commented on pdoc/__init__.py
> +        return annot.__name__
This is ill-posed if it's meant to match NewTypes only. In reality, this matches all functions, returning their names instead of reprs. I guess this is fine. But do amend the docstring.

2020-09-04 14:33 UTC, TristanCacqueray commented
Unfortunately `typing.get_type_hints()` mentioned in #231 does not seems to resolve NewType functions and they are still represented as `<function NewType.<locals>.new_type at 0x414141>`

2020-09-04 14:37 UTC, TristanCacqueray commented on pdoc/__init__.py
> +def formatannotation(annot):
Done

2020-09-04 14:42 UTC, TristanCacqueray commented on pdoc/__init__.py
> +        return annot.__name__
Indeed, I guess this is why the py3.5 test are failing. Next commit rewrites the function to better check for NewTypes.

2020-09-04 15:48 UTC, TristanCacqueray commented on pdoc/test/example_pkg/_resolve_typing_forwardrefs/evaluated.py
> +MyType = NewType('MyType', str)
To add more coverage, well next commit removes that change.

2020-09-04 15:58 UTC, TristanCacqueray commented on pdoc/test/example_pkg/__init__.py
> +    """NewType are correctly rendered"""
Not sure where in the tests this should be asserted.

2020-09-04 16:07 UTC, kernc commented on pdoc/test/example_pkg/__init__.py
> +    """NewType are correctly rendered"""
I think the addition to `test_Function_params()` (`bug253_newtype_annotation`) is enough as it covers and asserts. Can remove this hunk.

2020-09-04 16:10 UTC, TristanCacqueray commented on pdoc/test/example_pkg/__init__.py
> +    """NewType are correctly rendered"""
Removed.

2020-09-04 16:14 UTC, kernc commented on pdoc/__init__.py
> +    def is_new_type(annot):
A variable suffices:
```py
is_newtype = (... and ...)
```

2020-09-04 16:14 UTC, kernc commented on pdoc/__init__.py
> +    def is_new_type(annot):
And the expression can be `getattr(annot, '__qualname__', '').startswith('NewType.') and annot.__module__ == 'typing'`.

2020-09-04 16:16 UTC, TristanCacqueray commented on pdoc/__init__.py
> +    def is_new_type(annot):
Thank you for the suggestion, looks good to me.

2020-09-08 23:55 UTC, kernc commented on pdoc/__init__.py
> +                   annot.__module__ == 'typing')
```suggestion
                   getattr(annot, '__module__', '') == 'typing')
```

2020-09-08 23:59 UTC, kernc approved these changes

2020-09-08 23:59 UTC, kernc commented
Lgtm, thanks!

2020-09-09 00:00 UTC, merged