feat: Avoid trying to extract PEP-224 docstrings from builtins
pdoc3/pdoc pull request #258
Opened 2020-09-08 13:14 UTC by Hywan

If a module or a class is a builtin (e.g. from an extension), the
`_pep224_docstrings` function will generate a lot of warnings. This
patch skips the extraction of the PEP-224 docstrings for builtins
modules or classes.

2020-09-08 23:50 UTC, kernc requested changes
For the record, can you show an example project where "`_pep224_docstrings` function will generate a lot of warnings" on builtin types?

2020-09-08 23:50 UTC, kernc commented on pdoc/__init__.py
> +    is_builtins = type(doc_obj.obj).__module__ == 'builtins'
The tests fail because not all objects have `.__module__` attribute. Use `getattr()`?

2020-09-10 07:45 UTC, Hywan commented
> For the record, can you show an example project where "_pep224_docstrings function will generate a lot of warnings" on builtin types?

The wasmer-python project (https://github.com/wasmerio/wasmer-python/). For every module, class and function, there is a warning :-).

2020-09-14 14:13 UTC, Hywan commented
2 tests are failing:

```
======================================================================
FAIL: test_builtin_methoddescriptors (pdoc.test.ApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hywan/Development/pdoc/pdoc/test/__init__.py", line 521, in test_builtin_methoddescriptors
    c = pdoc.Class('STType', pdoc.Module(parser), parser.STType)
AssertionError: UserWarning not triggered

======================================================================
FAIL: test_class_variables_docstring_not_from_obj (pdoc.test.ApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hywan/Development/pdoc/pdoc/test/__init__.py", line 514, in test_class_variables_docstring_not_from_obj
    doc = pdoc.Class('C', pdoc.Module('pdoc'), C)
AssertionError: UserWarning not triggered

----------------------------------------------------------------------
```

Do you think they are still relevant?

2020-09-15 12:26 UTC, kernc commented
Surely relevant, but maybe dispose of their `assertWarns` context. `test_builtin_methoddescriptors` was somewhat erroneous (thanks!), so I dared to appropriate it in https://github.com/pdoc3/pdoc/commit/e9fd89f9a389c48d4252559b52b1017788446a7e. Maybe pull/rebase on master.

2020-09-15 12:27 UTC, kernc commented on pdoc/__init__.py
> +    is_builtins = type(doc_obj.obj).__module__ == 'builtins'
Let's move this below to where it's used, then.

2020-10-26 21:05 UTC, kernc approved these changes

2020-10-26 23:15 UTC, kernc commented
Merged with slight modification. Thanks!

2020-10-26 23:16 UTC, merged