Add support for variable docstrings starting with '#:'. Closes #289
pdoc3/pdoc pull request #292
Opened 2020-12-19 05:22 UTC by csm10495

I'd like to write a unit-test for this functionality, though I'm having some trouble running the existing suite: #291 

This basically matches up with sphinx behavior and a similar implementation.

2020-12-20 11:18 UTC, kernc requested changes
Looks neat! But definitely will need a unit test. :grimacing:

2020-12-20 11:18 UTC, kernc commented on pdoc/__init__.py
> +                comment_lines.append(assignment_line.rsplit('#:', 1)[-1])
Interestingly, this fails on a contrived line like:
```py
MARKER = '#:'  #: Doc-comment marker
```
Is this how Sphinx does it?

2020-12-20 11:18 UTC, kernc commented on pdoc/__init__.py
> +                vars[name] = '\n\n'.join(comment_lines)
I think this should be a single `\n`, otherwise it leaves blank lines between consecutive comment lines ...
```py
#: This long-winded text that stretches over multiple lines
#: should likely become a single documentation paragraph.
variable = 1
```
If you want to force line breaks (i.e. https://github.com/pdoc3/pdoc/issues/287), there are [ways for that](https://commonmark.org/help/tutorial/03-paragraphs.html) in markdown.

2020-12-21 00:56 UTC, csm10495 commented on pdoc/__init__.py
> +                vars[name] = '\n\n'.join(comment_lines)
Swapped to using 2 spaces at the end of each line.

2020-12-21 00:57 UTC, csm10495 commented on pdoc/__init__.py
> +            return len(line) - len(line.lstrip(' '))
Yep. You're right. I was still thinking of Python 2 where I had seen (obnoxious usage of tabs with spaces for indentation). Not needed in a Python 3 world.

2020-12-21 00:57 UTC, csm10495 commented on pdoc/__init__.py
> +            continue
Sure thing.

2020-12-21 00:58 UTC, csm10495 commented on pdoc/__init__.py
> +    Extracts PEP-224 and '#:' docstrings for variables of `doc_obj`
👍

2020-12-21 01:56 UTC, csm10495 commented
@kernc, added unit tests, fixed running on Windows. Let me know if it needs other changes. Otherwise feel free to merge.

2020-12-24 01:30 UTC, csm10495 commented
@kernc let me know if further changes are needed. Thanks!

2020-12-24 09:42 UTC, kernc commented on pdoc/test/__init__.py
> +class InlineVariableDocstringsTest(unittest.TestCase):
In like with current tests structure, I'd prefer all this merged into one single test case:
```py
#: Not included

#: Line 1
#: Line 2
var1 = 1  #: Line 3

#: Not included
var2 = 1
"""PEP-224 takes preference"""

class C
    #: class var
    class_var = 1
    
    def __init__(self):
       #: instance var
       self.instance_var = 1
```
e.g. in `pdoc.test.example_pkg._doccomments`, loaded simply like this test:
https://github.com/pdoc3/pdoc/blob/bec63077a03b2136e6982825d327073ed76cc20a/pdoc/test/__init__.py#L792-L798
and with its five or so assertions.

2020-12-24 13:34 UTC, csm10495 commented on pdoc/test/__init__.py
> -        PUBLIC_FILES = [i.replace('/', '\\') for i in PUBLIC_FILES]
Nope, unfortunately a couple tests were failing.  Some other places were using / so I updated here and in those places.

2020-12-24 13:41 UTC, csm10495 commented on pdoc/test/__init__.py
> +class InlineVariableDocstringsTest(unittest.TestCase):
That seems odd to me since if something is wrong, you don't immediately know what it is.

The way the tests I wrote are: if one piece (or case) fails you know based off the name, what happened. When throwing it all in one, you lose that granularity; you just know something is wrong.

Though since you prefer, I can shove it all in one case with one py file tested.

2020-12-24 13:50 UTC, csm10495 commented on pdoc/__init__.py
> +                vars[name] = '\n'.join([c + '  ' for c in comment_lines])
I disagree with this for my own usage, though if that's the desire: Ok. Will change.

2020-12-24 14:11 UTC, kernc commented on pdoc/test/__init__.py
> +class InlineVariableDocstringsTest(unittest.TestCase):
I know, but it's not such a major component to warrant a separate test class. The question I see relevant to cover is: _do the doc-comment docstrings work correctly or not_?

2020-12-24 14:15 UTC, kernc commented on pdoc/__init__.py
> +                vars[name] = '\n'.join([c + '  ' for c in comment_lines])
I understand, issue https://github.com/pdoc3/pdoc/issues/287. Your way makes it impossible to produce documentation paragraphs _without_ line breaks.
```py
#: I don't want to force new lines in prose documentation just
#: because I opted for line breaks in e.g. 69-column source.
```

2020-12-24 17:58 UTC, csm10495 commented on pdoc/__init__.py
> +                vars[name] = '\n'.join([c + '  ' for c in comment_lines])
Fair enough. You're right. In theory also adding a \ at the end would force a break so that help too.

2020-12-24 18:16 UTC, csm10495 commented on pdoc/test/__init__.py
> +class InlineVariableDocstringsTest(unittest.TestCase):
Ok. Will do

2020-12-24 18:20 UTC, csm10495 commented
@kernc I've made the requested changes. Let me know if it seems ok now. Thanks!

2020-12-26 09:59 UTC, kernc commented on pdoc/test/__init__.py
> +            self.assertEqual(instance_name_to_docs, {'instance_var': 'instance var'})
```suggestion
            mod = pdoc.Module(filename)
            self.assertEqual(mod.doc['var1'].docstring, 'Line 1\nLine 2\nLine 3')
            self.assertEqual(mod.doc['var2'].docstring, 'PEP-224 takes precedence')
            self.assertEqual(mod.doc['C'].docstring, '')
            self.assertEqual(mod.doc['C'].doc['class_var'].docstring, 'class var')
            self.assertEqual(mod.doc['C'].doc['instance_var'].docstring, 'instance var')
```

Let's use public API to cover, not the implementation details. Ad lib, maybe this passes.

2020-12-26 10:04 UTC, kernc commented
Now with this feature in place, amendment of documentation is in order:
https://github.com/pdoc3/pdoc/blob/28b366a57ae475168d5039d94470cda925066075/pdoc/documentation.md#L106-L137

2020-12-26 20:24 UTC, csm10495 commented on pdoc/test/__init__.py
> +            self.assertEqual(instance_name_to_docs, {'instance_var': 'instance var'})
Ok. Done.

2020-12-26 20:58 UTC, csm10495 commented
@kernc added documentation, fixed test. Please check again. Thanks.

2021-01-02 15:37 UTC, kernc commented
Applied with slight modification.

This is a great feature. Many thanks @csm10495! :sparkles:

2021-01-02 15:37 UTC, kernc approved these changes

2021-01-02 15:38 UTC, merged